spring.datasource.url=jdbc:postgresql://postgres:5432/foodcataloguedb
spring.datasource.username=postgres
spring.datasource.password=root

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true