spring.data.mongodb.uri=mongodb://mongodb:27017/orderdb

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG