#spring.data.mongodb.uri=mongodb://mongodb:27017/orderdb
#spring.data.mongodb.uri=mongodb+srv://rajdeepbasak2000_db_user:ZidF38rSr6TS5x0s@cluster0.gakxlxn.mongodb.net/orderdb?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.uri=${MONGO_URI}
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG